server:
  port: ${PORT}
  address: ${ADDRESS}

spring:
  application:
    name: UploadImageDemo
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    hibernate:
      ddlAuto: update
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB